### PR TITLE
Desktop and Mobile version

### PR DESCRIPTION
**Pull request by Simiran777**
# Overview
**Adding the HTML file to display the portfolio page - mobile and desktop version
**Adding the CSS file for the styling of the portfolio page - mobile and desktop version
** Fixed the errors using linters

# Why is the update required?
**This project helps in understanding the use of linters, Git & Github and Github flow and documenting the repo in a professional way. Thus, it should include error-free linter-checked files to display the functionality of linters.
** I updated the HTML and CSS files to make them more detailed and interactive.
**The design is made Microverse Students Figma Template for creative designing of the webpage.

# What changes does this update make?
** The code runs at the beginning to display a webpage page for my portfolio.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Hi @Simiran987 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

YesYouAreGIF (2)


## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay

## Required Changes ♻️
 - [ ] I noticed that you created a different `desktop.html` and `desktop.css`. Kindly use [media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) instead to modify your `mobile version` . Media queries are a key part of responsive web design, as they allow you to create different layouts depending on the size of the viewport. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Simiran777** [comment]
@frank1738 Actually I've used media queries and my desktop.html is a copy of my index.html (with a few changes that I've made), it's just that I didn't want to mess up my earlier made mobile version as I plan to experiment with it in near future😁                                  
                                   Also, when you check the files desktop.html and desktop.css do have the codes for both i.e. the mobile and the desktop versions✌🏻

**Review by ichala — CHANGES_REQUESTED** [review]
Hi @Simiran987 , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

the-simpsons-homer-simpson

## To Highlight 🎉

- Good Design✔️ 
- No linters Errors ✔️


 ## Required Changes ♻️

- [ ] First of all, you did a great job your website looks awesome and clean 🎉 , based on your comment, I saw in your desktop.css that you used media query already, and that file has both CSS for mobile and desktop, but still, your repo should look always professional and clean if you need to save some code for yourself kindly save it somewhere else locally and not in your repo, kindly rename the `desktop.html` to `index.html` and remove any unused code or files as mentioned by the previous reviewer, I tried to contact you through slack to explain more but couldn't reach you, anyways kindly try to implement the changes and you will be good to go, good luck 👏 

**********

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Simiran777** [comment]
@ichala Noted. Thank you for the review, I've made the required changes. Please kindly check.

**Comment by ichala** [comment]
@Simiran987 You can submit from your dashboard and another reviewer will check it  🙏

**Comment by ghost** [comment]
> @frank1738 Actually I've used media queries and my desktop.html is a copy of my index.html (with a few changes that I've made), it's just that I didn't want to mess up my earlier made mobile version as I plan to experiment with it in near future😁 Also, when you check the files desktop.html and desktop.css do have the codes for both i.e. the mobile and the desktop versions✌🏻

Okay., I probably checked the wrong file. My bad😁. But now your repo looks clean. Nice job👍

**Review by Alfredbis29 — APPROVED** [review]
### Hi @Simiran987 ,
  

 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! :tada:
 
 ## Highlights
:heavy_check_mark: Good commit history 
:heavy_check_mark: Linters are passing 
:heavy_check_mark: Very professional README 
:heavy_check_mark: Correct Github flow 
:heavy_check_mark: Descriptive PR

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
 Cheers and Happy coding! :clap: :clap: :clap:
  Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
